"""Initial migration - create all tables

Revision ID: 864ffbd2f5c4
Revises: 
Create Date: 2026-01-03 12:51:06.821133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '864ffbd2f5c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False, comment='CREATE, UPDATE, DELETE, VIEW, EXPORT, LOGIN, LOGOUT'),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Previous values (for UPDATE/DELETE)'),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='New values (for CREATE/UPDATE)'),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='Correlation ID for request tracing'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_type', sa.Enum('INCOME', 'EXPENSE', 'BOTH', name='categorytype'), nullable=False),
    sa.Column('wren_default', sa.Boolean(), nullable=False, comment='Default WREN tax-deductible status'),
    sa.Column('wren_review_required', sa.Boolean(), nullable=False, comment='Requires manual review for WREN compliance'),
    sa.Column('wren_notes', sa.Text(), nullable=True, comment='Notes on WREN classification'),
    sa.Column('vat_treatment', sa.Enum('STANDARD', 'ZERO_RATED', 'EXEMPT', 'OUT_OF_SCOPE', name='vattreatment'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'STARTER', 'PROFESSIONAL', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('business_entities',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('tin', sa.String(length=20), nullable=True, comment='Tax Identification Number'),
    sa.Column('rc_number', sa.String(length=20), nullable=True, comment='CAC Registration Number'),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False, comment='Month when fiscal year starts (1-12)'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_vat_registered', sa.Boolean(), nullable=False),
    sa.Column('vat_registration_date', sa.Date(), nullable=True),
    sa.Column('annual_turnover_threshold', sa.Boolean(), nullable=False, comment='True if turnover <= ₦50M (0% CIT eligible)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_business_entities_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_entities'))
    )
    op.create_index(op.f('ix_business_entities_tin'), 'business_entities', ['tin'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'ACCOUNTANT', 'AUDITOR', 'PAYROLL_MANAGER', 'INVENTORY_MANAGER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cit_records',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('gross_turnover', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('assessable_profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cit_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='0, 20, or 30 percent'),
    sa.Column('cit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('development_levy_applicable', sa.Boolean(), nullable=False),
    sa.Column('development_levy', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_tax_liability', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_filed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['business_entities.id'], name=op.f('fk_cit_records_entity_id_business_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cit_records'))
    )
    op.create_index(op.f('ix_cit_records_entity_id'), 'cit_records', ['entity_id'], unique=False)
    op.create_table('customers',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trading_name', sa.String(length=255), nullable=True),
    sa.Column('tin', sa.String(length=20), nullable=True, comment='Tax Identification Number (required for B2B e-invoicing)'),
    sa.Column('is_business', sa.Boolean(), nullable=False, comment='True for B2B, False for B2C'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['business_entities.id'], name=op.f('fk_customers_entity_id_business_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_entity_id'), 'customers', ['entity_id'], unique=False)
    op.create_index(op.f('ix_customers_tin'), 'customers', ['tin'], unique=False)
    op.create_table('inventory_items',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False, comment='Stock Keeping Unit'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=False, comment='Cost price per unit'),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='Selling price per unit'),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False, comment='Alert when stock falls below this level'),
    sa.Column('reorder_quantity', sa.Integer(), nullable=False, comment='Suggested quantity to reorder'),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False, comment='e.g., pcs, kg, liters'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_tracked', sa.Boolean(), nullable=False, comment='True if stock levels should be tracked'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['business_entities.id'], name=op.f('fk_inventory_items_entity_id_business_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items'))
    )
    op.create_index(op.f('ix_inventory_items_barcode'), 'inventory_items', ['barcode'], unique=False)
    op.create_index(op.f('ix_inventory_items_entity_id'), 'inventory_items', ['entity_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_sku'), 'inventory_items', ['sku'], unique=False)
    op.create_table('paye_records',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('employee_tin', sa.String(length=20), nullable=True),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('consolidated_relief', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('pension_contribution', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('nhf_contribution', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('other_reliefs', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('taxable_income', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('paye_tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['business_entities.id'], name=op.f('fk_paye_records_entity_id_business_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paye_records'))
    )
    op.create_index(op.f('ix_paye_records_entity_id'), 'paye_records', ['entity_id'], unique=False)
    op.create_table('tax_periods',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.Enum('MONTHLY', 'QUARTERLY', 'ANNUALLY', name='taxperiodtype'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True, comment='1-12 for monthly, NULL for annual'),
    sa.Column('quarter', sa.Integer(), nullable=True, comment='1-4 for quarterly, NULL otherwise'),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('is_filed', sa.Boolean(), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['business_entities.id'], name=op.f('fk_tax_periods_entity_id_business_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_periods'))
    )
    op.create_index(op.f('ix_tax_periods_entity_id'), 'tax_periods', ['entity_id'], unique=False)
    op.create_table('user_entity_access',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['business_entities.id'], name=op.f('fk_user_entity_access_entity_id_business_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_entity_access_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_entity_access'))
    )
    op.create_table('vendors',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trading_name', sa.String(length=255), nullable=True),
    sa.Column('tin', sa.String(length=20), nullable=True, comment='Tax Identification Number'),
    sa.Column('tin_verified', sa.Boolean(), nullable=False),
    sa.Column('tin_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tin_registered_name', sa.String(length=255), nullable=True, comment='Name returned from TIN verification'),
    sa.Column('is_vat_registered', sa.Boolean(), nullable=False, comment='True if vendor is VAT registered'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_number', sa.String(length=20), nullable=True),
    sa.Column('bank_account_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['business_entities.id'], name=op.f('fk_vendors_entity_id_business_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_index(op.f('ix_vendors_entity_id'), 'vendors', ['entity_id'], unique=False)
    op.create_index(op.f('ix_vendors_tin'), 'vendors', ['tin'], unique=False)
    op.create_table('invoices',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_treatment', sa.Enum('STANDARD', 'ZERO_RATED', 'EXEMPT', name='vattreatment'), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'SUBMITTED', 'ACCEPTED', 'REJECTED', 'DISPUTED', 'CANCELLED', 'PAID', 'PARTIALLY_PAID', name='invoicestatus'), nullable=False),
    sa.Column('nrs_irn', sa.String(length=100), nullable=True, comment='NRS Invoice Reference Number'),
    sa.Column('nrs_qr_code_data', sa.Text(), nullable=True, comment='QR code data from NRS'),
    sa.Column('nrs_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nrs_response', sa.Text(), nullable=True, comment='Raw NRS API response'),
    sa.Column('dispute_deadline', sa.DateTime(timezone=True), nullable=True, comment='Deadline for buyer dispute'),
    sa.Column('is_disputed', sa.Boolean(), nullable=False),
    sa.Column('dispute_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_invoices_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['business_entities.id'], name=op.f('fk_invoices_entity_id_business_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('nrs_irn', name=op.f('uq_invoices_nrs_irn'))
    )
    op.create_index(op.f('ix_invoices_entity_id'), 'invoices', ['entity_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('stock_movements',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('PURCHASE', 'SALE', 'ADJUSTMENT', 'TRANSFER', 'WRITE_OFF', 'RETURN', name='stockmovementtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Positive for inbound, negative for outbound'),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True, comment='PO number, invoice number, etc.'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_stock_movements_item_id_inventory_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    op.create_index(op.f('ix_stock_movements_item_id'), 'stock_movements', ['item_id'], unique=False)
    op.create_table('stock_write_offs',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason', sa.Enum('EXPIRED', 'DAMAGED', 'OBSOLETE', 'THEFT', 'OTHER', name='writeoffreason'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True, comment='Photos, inspection reports'),
    sa.Column('write_off_date', sa.Date(), nullable=False),
    sa.Column('is_tax_deductible', sa.Boolean(), nullable=False, comment='Eligible for tax deduction'),
    sa.Column('reviewed', sa.Boolean(), nullable=False, comment='Reviewed by accountant/auditor'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_stock_write_offs_item_id_inventory_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_write_offs'))
    )
    op.create_index(op.f('ix_stock_write_offs_item_id'), 'stock_write_offs', ['item_id'], unique=False)
    op.create_table('transactions',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', name='transactiontype'), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='Transaction amount in Naira'),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='VAT amount in Naira'),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='Total amount including VAT'),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True, comment='External reference number'),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('wren_status', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'REVIEW_REQUIRED', name='wrenstatus'), nullable=False),
    sa.Column('wren_notes', sa.Text(), nullable=True),
    sa.Column('vat_recoverable', sa.Boolean(), nullable=False, comment='True if Input VAT can be recovered'),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_frequency', sa.String(length=20), nullable=True, comment='monthly, quarterly, annually'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transactions_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['business_entities.id'], name=op.f('fk_transactions_entity_id_business_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_transactions_vendor_id_vendors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_entity_id'), 'transactions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_table('vat_records',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('tax_period_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('output_vat', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('input_vat_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('input_vat_recoverable', sa.Numeric(precision=15, scale=2), nullable=False, comment='VAT recoverable (WREN compliant expenses)'),
    sa.Column('input_vat_non_recoverable', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_vat_payable', sa.Numeric(precision=15, scale=2), nullable=False, comment='Output VAT - Recoverable Input VAT'),
    sa.Column('is_filed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['business_entities.id'], name=op.f('fk_vat_records_entity_id_business_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_period_id'], ['tax_periods.id'], name=op.f('fk_vat_records_tax_period_id_tax_periods'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vat_records'))
    )
    op.create_index(op.f('ix_vat_records_entity_id'), 'vat_records', ['entity_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_line_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line_items'))
    )
    op.create_table('wht_records',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('vendor_tin', sa.String(length=20), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('wht_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='5% or 10% depending on category'),
    sa.Column('wht_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_exempt', sa.Boolean(), nullable=False, comment='True if transaction < ₦2M (small business exemption)'),
    sa.Column('deduction_date', sa.Date(), nullable=False),
    sa.Column('is_remitted', sa.Boolean(), nullable=False),
    sa.Column('remittance_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['business_entities.id'], name=op.f('fk_wht_records_entity_id_business_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_wht_records_transaction_id_transactions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wht_records'))
    )
    op.create_index(op.f('ix_wht_records_entity_id'), 'wht_records', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wht_records_entity_id'), table_name='wht_records')
    op.drop_table('wht_records')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_vat_records_entity_id'), table_name='vat_records')
    op.drop_table('vat_records')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_entity_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_stock_write_offs_item_id'), table_name='stock_write_offs')
    op.drop_table('stock_write_offs')
    op.drop_index(op.f('ix_stock_movements_item_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_entity_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_vendors_tin'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_entity_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_table('user_entity_access')
    op.drop_index(op.f('ix_tax_periods_entity_id'), table_name='tax_periods')
    op.drop_table('tax_periods')
    op.drop_index(op.f('ix_paye_records_entity_id'), table_name='paye_records')
    op.drop_table('paye_records')
    op.drop_index(op.f('ix_inventory_items_sku'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_entity_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_barcode'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_customers_tin'), table_name='customers')
    op.drop_index(op.f('ix_customers_entity_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_cit_records_entity_id'), table_name='cit_records')
    op.drop_table('cit_records')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_business_entities_tin'), table_name='business_entities')
    op.drop_table('business_entities')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('categories')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
