"""
Seed Data: Vendors for Efe Obus Furniture Manufacturing LTD
============================================================
20 Vendors/Suppliers - Raw materials, services, and utilities
"""

# =============================================================================
# VENDORS DATA (20 vendors)
# =============================================================================

VENDORS_DATA = [
    # =========================================================================
    # RAW MATERIAL SUPPLIERS
    # =========================================================================
    {
        "name": "Ondo State Timber Trading Company",
        "trading_name": "OSTTC",
        "tin": "VEN-TIN-001234",
        "tin_verified": True,
        "is_vat_registered": True,
        "default_wht_rate": 5.0,
        "contact_person": "Chief Adebayo Timber",
        "email": "sales@osttc.com.ng",
        "phone": "+234 803 111 2222",
        "address": "Timber Market, Ondo Road",
        "city": "Ondo",
        "state": "Ondo",
        "bank_name": "First Bank",
        "bank_account_number": "2011223344",
        "bank_account_name": "Ondo State Timber Trading Company",
        "notes": "Primary hardwood supplier - mahogany, iroko, obeche",
    },
    {
        "name": "Lagos Plywood Industries",
        "trading_name": "LPI",
        "tin": "VEN-TIN-002345",
        "tin_verified": True,
        "is_vat_registered": True,
        "default_wht_rate": 5.0,
        "contact_person": "Mr. Chen Wei",
        "email": "orders@lagosplywood.com",
        "phone": "+234 1 234 5678",
        "address": "Plot 15, Apapa Industrial Estate",
        "city": "Lagos",
        "state": "Lagos",
        "bank_name": "GTBank",
        "bank_account_number": "0122334455",
        "bank_account_name": "Lagos Plywood Industries Ltd",
        "notes": "Plywood and MDF supplier",
    },
    {
        "name": "Kano Leather Works",
        "trading_name": "KLW",
        "tin": "VEN-TIN-003456",
        "tin_verified": True,
        "is_vat_registered": True,
        "default_wht_rate": 5.0,
        "contact_person": "Alhaji Garba Musa",
        "email": "sales@kanoleather.com",
        "phone": "+234 803 222 3333",
        "address": "Sabon Gari Industrial Area",
        "city": "Kano",
        "state": "Kano",
        "bank_name": "Zenith Bank",
        "bank_account_number": "1033445566",
        "bank_account_name": "Kano Leather Works Ltd",
        "notes": "Premium leather for upholstery",
    },
    {
        "name": "Delta Foam Industries",
        "trading_name": "DFI",
        "tin": "VEN-TIN-004567",
        "tin_verified": True,
        "is_vat_registered": True,
        "default_wht_rate": 5.0,
        "contact_person": "Chief Okonkwo Mike",
        "email": "sales@deltafoam.com.ng",
        "phone": "+234 803 333 4444",
        "address": "Industrial Layout, Warri-Sapele Road",
        "city": "Warri",
        "state": "Delta",
        "bank_name": "Access Bank",
        "bank_account_number": "0144556677",
        "bank_account_name": "Delta Foam Industries Ltd",
        "notes": "Foam and cushioning materials",
    },
    {
        "name": "Onitsha Fabric Merchants",
        "trading_name": "OFM",
        "tin": "VEN-TIN-005678",
        "tin_verified": True,
        "is_vat_registered": True,
        "default_wht_rate": 5.0,
        "contact_person": "Mrs. Nkechi Okafor",
        "email": "fabric@ofm.com.ng",
        "phone": "+234 803 444 5555",
        "address": "Main Market, Onitsha",
        "city": "Onitsha",
        "state": "Anambra",
        "bank_name": "UBA",
        "bank_account_number": "2055667788",
        "bank_account_name": "Onitsha Fabric Merchants",
        "notes": "Upholstery fabrics and textiles",
    },
    {
        "name": "Hardware Plus Nigeria",
        "trading_name": "HPN",
        "tin": "VEN-TIN-006789",
        "tin_verified": True,
        "is_vat_registered": True,
        "default_wht_rate": 5.0,
        "contact_person": "Mr. Abiodun Lawal",
        "email": "orders@hardwareplus.ng",
        "phone": "+234 803 555 6666",
        "address": "Allen Avenue, Ikeja",
        "city": "Lagos",
        "state": "Lagos",
        "bank_name": "Fidelity Bank",
        "bank_account_number": "5066778899",
        "bank_account_name": "Hardware Plus Nigeria Ltd",
        "notes": "Screws, hinges, handles, locks - furniture hardware",
    },
    {
        "name": "Supreme Varnish & Coatings",
        "trading_name": "SVC",
        "tin": "VEN-TIN-007890",
        "tin_verified": True,
        "is_vat_registered": True,
        "default_wht_rate": 5.0,
        "contact_person": "Dr. Emeka Nwachukwu",
        "email": "sales@supremevarnish.com",
        "phone": "+234 803 666 7777",
        "address": "Trans Amadi Industrial Layout",
        "city": "Port Harcourt",
        "state": "Rivers",
        "bank_name": "Sterling Bank",
        "bank_account_number": "0077889900",
        "bank_account_name": "Supreme Varnish & Coatings Ltd",
        "notes": "Wood varnish, lacquer, stains, and finishing products",
    },
    {
        "name": "Glass Masters Nigeria",
        "trading_name": "GMN",
        "tin": "VEN-TIN-008901",
        "tin_verified": True,
        "is_vat_registered": True,
        "default_wht_rate": 5.0,
        "contact_person": "Mr. Abdul Mohammed",
        "email": "sales@glassmasters.ng",
        "phone": "+234 803 777 8888",
        "address": "Oregun Industrial Estate",
        "city": "Lagos",
        "state": "Lagos",
        "bank_name": "Stanbic IBTC",
        "bank_account_number": "0088990011",
        "bank_account_name": "Glass Masters Nigeria Ltd",
        "notes": "Tempered glass for tables and cabinets",
    },
    
    # =========================================================================
    # EQUIPMENT & MACHINERY SUPPLIERS
    # =========================================================================
    {
        "name": "Woodworking Machines Nigeria",
        "trading_name": "WMN",
        "tin": "VEN-TIN-009012",
        "tin_verified": True,
        "is_vat_registered": True,
        "default_wht_rate": 10.0,
        "contact_person": "Engr. Tunde Makinde",
        "email": "sales@wmn.com.ng",
        "phone": "+234 803 888 9999",
        "address": "Ota Industrial Estate",
        "city": "Ota",
        "state": "Ogun",
        "bank_name": "FCMB",
        "bank_account_number": "1099001122",
        "bank_account_name": "Woodworking Machines Nigeria Ltd",
        "notes": "CNC machines, sanders, planers, saws - maintenance contracts",
    },
    {
        "name": "Power Tools Express",
        "trading_name": "PTE",
        "tin": "VEN-TIN-010123",
        "tin_verified": True,
        "is_vat_registered": True,
        "default_wht_rate": 5.0,
        "contact_person": "Mr. James Ogundimu",
        "email": "orders@powertoolsexpress.ng",
        "phone": "+234 803 999 0000",
        "address": "Alaba International Market",
        "city": "Lagos",
        "state": "Lagos",
        "bank_name": "Wema Bank",
        "bank_account_number": "0100112233",
        "bank_account_name": "Power Tools Express Ltd",
        "notes": "Hand tools and power tools",
    },
    
    # =========================================================================
    # SERVICES SUPPLIERS
    # =========================================================================
    {
        "name": "BEDC Electricity",
        "trading_name": "BEDC",
        "tin": "VEN-TIN-011234",
        "tin_verified": True,
        "is_vat_registered": True,
        "contact_person": "Customer Service",
        "email": "customercare@bedcpower.com",
        "phone": "+234 800 232 2000",
        "address": "BEDC Office, Benin City",
        "city": "Benin City",
        "state": "Edo",
        "notes": "Electricity bills - primary utility",
    },
    {
        "name": "Shell Nigeria Gas",
        "trading_name": "SNG",
        "tin": "VEN-TIN-012345",
        "tin_verified": True,
        "is_vat_registered": True,
        "contact_person": "Mr. Dele Fashola",
        "email": "industrial@shellnigeria.com",
        "phone": "+234 84 230 0000",
        "address": "Shell Industrial Gas Division",
        "city": "Port Harcourt",
        "state": "Rivers",
        "notes": "Industrial gas for finishing processes",
    },
    {
        "name": "Total Nigeria - Fuel",
        "trading_name": "Total Fuel",
        "tin": "VEN-TIN-013456",
        "tin_verified": True,
        "is_vat_registered": True,
        "contact_person": "Mr. Femi Adeyinka",
        "email": "corporate@total.com.ng",
        "phone": "+234 1 271 0000",
        "address": "Total Corporate Office, Victoria Island",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Diesel for generators and fleet",
    },
    {
        "name": "Hallmark Insurance",
        "trading_name": "Hallmark HMO",
        "tin": "VEN-TIN-014567",
        "tin_verified": True,
        "is_vat_registered": True,
        "contact_person": "Mrs. Nneka Eze",
        "email": "corporate@hallmarkinsurance.com.ng",
        "phone": "+234 1 280 5000",
        "address": "Hallmark Building, Ilupeju",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Insurance - property, vehicles, group life",
    },
    {
        "name": "AIICO Insurance",
        "trading_name": "AIICO",
        "tin": "VEN-TIN-015678",
        "tin_verified": True,
        "is_vat_registered": True,
        "contact_person": "Mr. Babatunde Coker",
        "email": "corporate@aiicoplc.com",
        "phone": "+234 1 279 0000",
        "address": "AIICO Plaza, Victoria Island",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Workmen compensation and fire insurance",
    },
    {
        "name": "MTN Business",
        "trading_name": "MTN",
        "tin": "VEN-TIN-016789",
        "tin_verified": True,
        "is_vat_registered": True,
        "contact_person": "MTN Corporate",
        "email": "business@mtn.com.ng",
        "phone": "+234 803 000 0000",
        "address": "MTN Head Office",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Telecommunications - mobile and internet",
    },
    {
        "name": "Andela Security Services",
        "trading_name": "ASS",
        "tin": "VEN-TIN-017890",
        "tin_verified": True,
        "is_vat_registered": True,
        "default_wht_rate": 5.0,
        "contact_person": "Col. Ret. Musa Danjuma",
        "email": "operations@andelasecurity.ng",
        "phone": "+234 803 123 0000",
        "address": "Ikorodu Road, Lagos",
        "city": "Lagos",
        "state": "Lagos",
        "bank_name": "Union Bank",
        "bank_account_number": "0011223344",
        "bank_account_name": "Andela Security Services Ltd",
        "notes": "Factory security services",
    },
    {
        "name": "CleanMax Services",
        "trading_name": "CleanMax",
        "tin": "VEN-TIN-018901",
        "tin_verified": True,
        "is_vat_registered": True,
        "default_wht_rate": 5.0,
        "contact_person": "Mrs. Joy Amaechi",
        "email": "services@cleanmax.ng",
        "phone": "+234 803 234 0000",
        "address": "Surulere, Lagos",
        "city": "Lagos",
        "state": "Lagos",
        "bank_name": "Polaris Bank",
        "bank_account_number": "1122334455",
        "bank_account_name": "CleanMax Services Ltd",
        "notes": "Office and factory cleaning services",
    },
    {
        "name": "Express Logistics Nigeria",
        "trading_name": "ELN",
        "tin": "VEN-TIN-019012",
        "tin_verified": True,
        "is_vat_registered": True,
        "default_wht_rate": 5.0,
        "contact_person": "Mr. Chukwuma Okoro",
        "email": "dispatch@expresslogistics.ng",
        "phone": "+234 803 345 0000",
        "address": "Apapa Wharf Road",
        "city": "Lagos",
        "state": "Lagos",
        "bank_name": "Keystone Bank",
        "bank_account_number": "6011223344",
        "bank_account_name": "Express Logistics Nigeria Ltd",
        "notes": "Furniture delivery and logistics partner",
    },
    {
        "name": "Adeyemi & Associates",
        "trading_name": "A&A Legal",
        "tin": "VEN-TIN-020123",
        "tin_verified": True,
        "is_vat_registered": False,
        "default_wht_rate": 10.0,
        "contact_person": "Barrister Adeyemi Johnson",
        "email": "partners@adeyemilegal.ng",
        "phone": "+234 1 456 7890",
        "address": "Law House, Victoria Island",
        "city": "Lagos",
        "state": "Lagos",
        "bank_name": "GTBank",
        "bank_account_number": "0123456789",
        "bank_account_name": "Adeyemi & Associates",
        "notes": "Legal services and corporate advisory",
    },
]
