"""
Seed Data: Customers for Efe Obus Furniture Manufacturing LTD
==============================================================
35 Customers - Mix of B2B (corporate) and B2C (individual) customers
"""

# =============================================================================
# CUSTOMERS DATA (35 customers - 20 B2B, 15 B2C)
# =============================================================================

CUSTOMERS_DATA = [
    # =========================================================================
    # B2B CUSTOMERS (Corporate/Business) - 20 customers
    # =========================================================================
    {
        "name": "Shoprite Nigeria",
        "trading_name": "Shoprite Holdings",
        "tin": "TIN-SHP-001234",
        "is_business": True,
        "email": "procurement@shoprite.com.ng",
        "phone": "+234 1 270 0000",
        "contact_person": "Mr. Adebayo Olumide",
        "address": "1, Adeniran Ogunsanya, Surulere",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Major retail chain - bulk furniture orders for new stores",
    },
    {
        "name": "Dangote Industries Limited",
        "trading_name": "Dangote Group",
        "tin": "TIN-DAN-005678",
        "is_business": True,
        "email": "facilities@dangote.com",
        "phone": "+234 1 448 0000",
        "contact_person": "Engr. Musa Ibrahim",
        "address": "Dangote Refinery, Lekki Free Trade Zone",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Office furniture for corporate headquarters and facilities",
    },
    {
        "name": "Access Bank PLC",
        "trading_name": "Access Bank",
        "tin": "TIN-ACB-009012",
        "is_business": True,
        "email": "admin@accessbankplc.com",
        "phone": "+234 1 280 5000",
        "contact_person": "Mrs. Funke Adewale",
        "address": "Access Bank Tower, Danmole Street, Victoria Island",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Banking hall furniture and executive office sets",
    },
    {
        "name": "Zenith Bank PLC",
        "trading_name": "Zenith Bank",
        "tin": "TIN-ZEN-003456",
        "is_business": True,
        "email": "procurement@zenithbank.com",
        "phone": "+234 1 278 1000",
        "contact_person": "Mr. Chidi Emenike",
        "address": "Zenith Heights, Victoria Island",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Branch furniture upgrades - quarterly orders",
    },
    {
        "name": "Nigerian Breweries PLC",
        "trading_name": "NB PLC",
        "tin": "TIN-NBP-007890",
        "is_business": True,
        "email": "facilities@nbplc.com",
        "phone": "+234 1 271 0300",
        "contact_person": "Mr. Hans Mueller",
        "address": "1, Abebe Village Road, Iganmu",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Lounge and conference furniture",
    },
    {
        "name": "University of Benin",
        "trading_name": "UNIBEN",
        "tin": "TIN-UNB-002345",
        "is_business": True,
        "email": "bursary@uniben.edu",
        "phone": "+234 52 600 151",
        "contact_person": "Prof. Osahon Igbinovia",
        "address": "University of Benin, Ugbowo Campus",
        "city": "Benin City",
        "state": "Edo",
        "notes": "Lecture hall seating and office furniture",
    },
    {
        "name": "Federal Medical Centre Asaba",
        "trading_name": "FMC Asaba",
        "tin": "TIN-FMC-004567",
        "is_business": True,
        "email": "admin@fmcasaba.gov.ng",
        "phone": "+234 56 280 000",
        "contact_person": "Dr. Emeka Okolie",
        "address": "Nnebisi Road, Asaba",
        "city": "Asaba",
        "state": "Delta",
        "notes": "Hospital furniture - waiting areas and offices",
    },
    {
        "name": "Delta State Government",
        "trading_name": "DSG Secretariat",
        "tin": "TIN-DSG-006789",
        "is_business": True,
        "email": "procurement@deltastate.gov.ng",
        "phone": "+234 56 230 000",
        "contact_person": "Mrs. Patricia Okolie",
        "address": "Government House, Asaba",
        "city": "Asaba",
        "state": "Delta",
        "notes": "Government office furniture contracts",
    },
    {
        "name": "Sterling Oil Exploration & Energy",
        "trading_name": "Sterling Oil",
        "tin": "TIN-STE-008901",
        "is_business": True,
        "email": "admin@sterlingoil.com.ng",
        "phone": "+234 84 230 000",
        "contact_person": "Mr. Tobenna Okoye",
        "address": "Trans Amadi Industrial Layout",
        "city": "Port Harcourt",
        "state": "Rivers",
        "notes": "Executive office furniture for oil & gas offices",
    },
    {
        "name": "Total Energies Nigeria",
        "trading_name": "TotalEnergies",
        "tin": "TIN-TOT-001234",
        "is_business": True,
        "email": "procurement@totalenergies.com.ng",
        "phone": "+234 1 270 4000",
        "contact_person": "Ms. Chinyere Obi",
        "address": "Total House, Plot 25, Trans Amadi",
        "city": "Port Harcourt",
        "state": "Rivers",
        "notes": "Premium office and lounge furniture",
    },
    {
        "name": "Marriott Hotels Nigeria",
        "trading_name": "Marriott International",
        "tin": "TIN-MAR-003456",
        "is_business": True,
        "email": "procurement@marriott.com.ng",
        "phone": "+234 1 448 9000",
        "contact_person": "Mr. James Adeyemi",
        "address": "122, Joel Ogunnaike Street, Ikeja GRA",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Hotel room furniture and lobby sets - premium quality",
    },
    {
        "name": "Radisson Blu Anchorage",
        "trading_name": "Radisson Hotels",
        "tin": "TIN-RAD-005678",
        "is_business": True,
        "email": "purchasing@radisson.com.ng",
        "phone": "+234 1 448 5000",
        "contact_person": "Mrs. Sandra Ibe",
        "address": "1A, Ozumba Mbadiwe Avenue, Victoria Island",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Conference room and guest room furniture",
    },
    {
        "name": "Transcorp Hilton Abuja",
        "trading_name": "Transcorp Hotels",
        "tin": "TIN-TRH-007890",
        "is_business": True,
        "email": "procurement@transcorphotels.com",
        "phone": "+234 9 461 5000",
        "contact_person": "Mr. Aliyu Mohammed",
        "address": "1, Aguiyi Ironsi Street, Maitama",
        "city": "Abuja",
        "state": "FCT",
        "notes": "Luxury suite furniture renovation project",
    },
    {
        "name": "Oando PLC",
        "trading_name": "Oando Energy",
        "tin": "TIN-OAN-002345",
        "is_business": True,
        "email": "facilities@oandoplc.com",
        "phone": "+234 1 270 1234",
        "contact_person": "Engr. Femi Akinola",
        "address": "Oando Tower, Lekki Phase 1",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Corporate HQ furniture upgrade",
    },
    {
        "name": "Nigerian National Petroleum Company",
        "trading_name": "NNPC Limited",
        "tin": "TIN-NNP-004567",
        "is_business": True,
        "email": "procurement@nnpcgroup.com",
        "phone": "+234 9 413 7000",
        "contact_person": "Mrs. Amina Yusuf",
        "address": "NNPC Towers, Herbert Macaulay Way",
        "city": "Abuja",
        "state": "FCT",
        "notes": "Office furniture for regional offices",
    },
    {
        "name": "Guaranty Trust Bank",
        "trading_name": "GTBank",
        "tin": "TIN-GTB-006789",
        "is_business": True,
        "email": "admin@gtbank.com",
        "phone": "+234 1 448 0000",
        "contact_person": "Mr. Tunde Bakare",
        "address": "Plot 635, Akin Adesola Street, Victoria Island",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Modern banking furniture - quarterly supplies",
    },
    {
        "name": "Airtel Nigeria",
        "trading_name": "Airtel",
        "tin": "TIN-AIR-008901",
        "is_business": True,
        "email": "procurement@airtel.com.ng",
        "phone": "+234 802 150 0000",
        "contact_person": "Ms. Ngozi Okoli",
        "address": "Airtel Tower, Banana Island Road",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Call center furniture and office equipment",
    },
    {
        "name": "MTN Nigeria",
        "trading_name": "MTN Communications",
        "tin": "TIN-MTN-001234",
        "is_business": True,
        "email": "procurement@mtn.com.ng",
        "phone": "+234 803 000 0000",
        "contact_person": "Mr. Oluwaseun Adeyinka",
        "address": "MTN Plaza, Falomo, Ikoyi",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Regional office furniture rollout",
    },
    {
        "name": "First City Monument Bank",
        "trading_name": "FCMB",
        "tin": "TIN-FCM-003456",
        "is_business": True,
        "email": "facilities@fcmb.com",
        "phone": "+234 1 279 0000",
        "contact_person": "Mrs. Bukola Adeniyi",
        "address": "FCMB Head Office, Marina",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Branch renovation furniture",
    },
    {
        "name": "Flour Mills of Nigeria",
        "trading_name": "FMN PLC",
        "tin": "TIN-FMN-005678",
        "is_business": True,
        "email": "admin@fmnplc.com",
        "phone": "+234 1 271 0200",
        "contact_person": "Mr. Kayode Omotosho",
        "address": "2, Old Dock Road, Apapa",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Executive office and boardroom furniture",
    },
    
    # =========================================================================
    # B2C CUSTOMERS (Individual/Retail) - 15 customers
    # =========================================================================
    {
        "name": "Chief Emmanuel Okonkwo",
        "is_business": False,
        "email": "emmanuel.okonkwo@gmail.com",
        "phone": "+234 803 123 4567",
        "address": "12 Victoria Garden City",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "High-net-worth individual - luxury home furniture",
    },
    {
        "name": "Dr. Adaeze Umeh",
        "is_business": False,
        "email": "dr.umeh@yahoo.com",
        "phone": "+234 806 234 5678",
        "address": "45 GRA Extension",
        "city": "Benin City",
        "state": "Edo",
        "notes": "Home office and living room furniture",
    },
    {
        "name": "Barrister Chukwudi Eze",
        "is_business": False,
        "email": "chukwudi.eze@lawfirm.ng",
        "phone": "+234 807 345 6789",
        "address": "8 Legal Lane, Independence Layout",
        "city": "Enugu",
        "state": "Enugu",
        "notes": "Home library and study furniture",
    },
    {
        "name": "Mrs. Funmilayo Adeyemi",
        "is_business": False,
        "email": "funmi.adeyemi@hotmail.com",
        "phone": "+234 808 456 7890",
        "address": "23 Magodo Phase 2",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Bedroom and dining room sets",
    },
    {
        "name": "Alhaji Yusuf Abubakar",
        "is_business": False,
        "email": "yusuf.abubakar@gmail.com",
        "phone": "+234 809 567 8901",
        "address": "15 Asokoro Extension",
        "city": "Abuja",
        "state": "FCT",
        "notes": "Complete home furnishing - new residence",
    },
    {
        "name": "Prof. Olumide Fashola",
        "is_business": False,
        "email": "prof.fashola@unilag.edu.ng",
        "phone": "+234 810 678 9012",
        "address": "University of Lagos Staff Quarters",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Home office and study furniture",
    },
    {
        "name": "Engr. Ngozi Okafor",
        "is_business": False,
        "email": "ngozi.okafor@engineering.ng",
        "phone": "+234 811 789 0123",
        "address": "10 Trans Amadi",
        "city": "Port Harcourt",
        "state": "Rivers",
        "notes": "Living room and outdoor furniture",
    },
    {
        "name": "Mr. Patrick Ikenna",
        "is_business": False,
        "email": "patrick.ikenna@gmail.com",
        "phone": "+234 812 890 1234",
        "address": "32 New Haven",
        "city": "Enugu",
        "state": "Enugu",
        "notes": "Kitchen and dining furniture",
    },
    {
        "name": "Mrs. Grace Adeleke",
        "is_business": False,
        "email": "grace.adeleke@outlook.com",
        "phone": "+234 813 901 2345",
        "address": "7 Bodija Estate",
        "city": "Ibadan",
        "state": "Oyo",
        "notes": "Children's bedroom furniture",
    },
    {
        "name": "Dr. Ibrahim Musa",
        "is_business": False,
        "email": "ibrahim.musa@health.ng",
        "phone": "+234 814 012 3456",
        "address": "44 Wuse Zone 5",
        "city": "Abuja",
        "state": "FCT",
        "notes": "Living room set and home office",
    },
    {
        "name": "Chief Mrs. Obiageli Nnamdi",
        "is_business": False,
        "email": "obiageli.nnamdi@gmail.com",
        "phone": "+234 815 123 4567",
        "address": "15 Aguata Street, Onitsha",
        "city": "Onitsha",
        "state": "Anambra",
        "notes": "Traditional and modern furniture blend",
    },
    {
        "name": "Mr. Samuel Okonjo",
        "is_business": False,
        "email": "samuel.okonjo@tech.ng",
        "phone": "+234 816 234 5678",
        "address": "9 Lekki Phase 1",
        "city": "Lagos",
        "state": "Lagos",
        "notes": "Modern minimalist furniture",
    },
    {
        "name": "Mrs. Amina Bello",
        "is_business": False,
        "email": "amina.bello@gmail.com",
        "phone": "+234 817 345 6789",
        "address": "28 GRA Kaduna",
        "city": "Kaduna",
        "state": "Kaduna",
        "notes": "Guest room and parlor furniture",
    },
    {
        "name": "Mr. Emeka Obi",
        "is_business": False,
        "email": "emeka.obi@business.ng",
        "phone": "+234 818 456 7890",
        "address": "55 Aba Road",
        "city": "Port Harcourt",
        "state": "Rivers",
        "notes": "Executive home office setup",
    },
    {
        "name": "Dr. Fatima Abdullahi",
        "is_business": False,
        "email": "fatima.abdullahi@med.ng",
        "phone": "+234 819 567 8901",
        "address": "12 Maitama District",
        "city": "Abuja",
        "state": "FCT",
        "notes": "Complete apartment furnishing",
    },
]
