"""
Seed Data: Fixed Assets for Efe Obus Furniture Manufacturing LTD
=================================================================
Manufacturing equipment, vehicles, buildings, and other capital assets
"""

from datetime import date
from decimal import Decimal

# Import enums from the model
from app.models.fixed_asset import AssetCategory, DepreciationMethod

# =============================================================================
# FIXED ASSETS DATA (25+ assets)
# =============================================================================

FIXED_ASSETS_DATA = [
    # =========================================================================
    # LAND & BUILDINGS
    # =========================================================================
    {
        "asset_code": "FA-LAND-001",
        "name": "Factory Land - Plot 45 Industrial Layout",
        "description": "5 acres of land at Industrial Layout, Agbor",
        "category": AssetCategory.LAND,
        "location": "Industrial Layout, Agbor",
        "department": "Administration",
        "acquisition_date": date(2015, 3, 15),
        "acquisition_cost": Decimal("150000000.00"),
        "depreciation_method": DepreciationMethod.STRAIGHT_LINE,
        "depreciation_rate": Decimal("0"),
        "useful_life_years": 0,
        "residual_value": Decimal("150000000.00"),
    },
    {
        "asset_code": "FA-BLDG-001",
        "name": "Main Factory Building",
        "description": "20,000 sq ft production facility",
        "category": AssetCategory.BUILDINGS,
        "location": "Industrial Layout, Agbor",
        "department": "Production",
        "acquisition_date": date(2016, 1, 10),
        "acquisition_cost": Decimal("120000000.00"),
        "depreciation_method": DepreciationMethod.STRAIGHT_LINE,
        "depreciation_rate": Decimal("10"),
        "useful_life_years": 50,
        "residual_value": Decimal("12000000.00"),
    },
    {
        "asset_code": "FA-BLDG-002",
        "name": "Warehouse Building",
        "description": "10,000 sq ft finished goods warehouse",
        "category": AssetCategory.BUILDINGS,
        "location": "Industrial Layout, Agbor",
        "department": "Warehouse",
        "acquisition_date": date(2018, 6, 20),
        "acquisition_cost": Decimal("45000000.00"),
        "depreciation_method": DepreciationMethod.STRAIGHT_LINE,
        "depreciation_rate": Decimal("10"),
        "useful_life_years": 50,
        "residual_value": Decimal("4500000.00"),
    },
    {
        "asset_code": "FA-BLDG-003",
        "name": "Administrative Office Block",
        "description": "2-storey office building",
        "category": AssetCategory.BUILDINGS,
        "location": "Industrial Layout, Agbor",
        "department": "Administration",
        "acquisition_date": date(2017, 4, 5),
        "acquisition_cost": Decimal("35000000.00"),
        "depreciation_method": DepreciationMethod.STRAIGHT_LINE,
        "depreciation_rate": Decimal("10"),
        "useful_life_years": 50,
        "residual_value": Decimal("3500000.00"),
    },
    {
        "asset_code": "FA-BLDG-004",
        "name": "Showroom Building",
        "description": "Furniture showroom on main road",
        "category": AssetCategory.BUILDINGS,
        "location": "Agbor-Obi Road, Agbor",
        "department": "Sales",
        "acquisition_date": date(2019, 9, 1),
        "acquisition_cost": Decimal("28000000.00"),
        "depreciation_method": DepreciationMethod.STRAIGHT_LINE,
        "depreciation_rate": Decimal("10"),
        "useful_life_years": 50,
        "residual_value": Decimal("2800000.00"),
    },
    
    # =========================================================================
    # PLANT & MACHINERY
    # =========================================================================
    {
        "asset_code": "FA-MACH-001",
        "name": "CNC Wood Router Machine",
        "description": "5-axis CNC router for precision cutting",
        "category": AssetCategory.PLANT_MACHINERY,
        "location": "Production Floor - Bay 1",
        "department": "Production",
        "acquisition_date": date(2020, 2, 15),
        "acquisition_cost": Decimal("18500000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 10,
        "residual_value": Decimal("1850000.00"),
        "vendor_name": "Woodworking Machines Nigeria",
        "vendor_invoice_number": "WMN-2020-0234",
    },
    {
        "asset_code": "FA-MACH-002",
        "name": "Industrial Panel Saw",
        "description": "Sliding table panel saw for sheet cutting",
        "category": AssetCategory.PLANT_MACHINERY,
        "location": "Production Floor - Bay 2",
        "department": "Production",
        "acquisition_date": date(2019, 5, 10),
        "acquisition_cost": Decimal("8500000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 10,
        "residual_value": Decimal("850000.00"),
        "vendor_name": "Woodworking Machines Nigeria",
        "vendor_invoice_number": "WMN-2019-0156",
    },
    {
        "asset_code": "FA-MACH-003",
        "name": "Industrial Wood Planer",
        "description": "Heavy-duty thickness planer",
        "category": AssetCategory.PLANT_MACHINERY,
        "location": "Production Floor - Bay 2",
        "department": "Production",
        "acquisition_date": date(2018, 8, 22),
        "acquisition_cost": Decimal("4500000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 10,
        "residual_value": Decimal("450000.00"),
    },
    {
        "asset_code": "FA-MACH-004",
        "name": "Edge Banding Machine",
        "description": "Automatic edge banding for MDF and particle board",
        "category": AssetCategory.PLANT_MACHINERY,
        "location": "Production Floor - Bay 3",
        "department": "Production",
        "acquisition_date": date(2021, 3, 8),
        "acquisition_cost": Decimal("6500000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 10,
        "residual_value": Decimal("650000.00"),
    },
    {
        "asset_code": "FA-MACH-005",
        "name": "Spray Booth System",
        "description": "Industrial spray booth for finishing",
        "category": AssetCategory.PLANT_MACHINERY,
        "location": "Finishing Department",
        "department": "Production",
        "acquisition_date": date(2020, 7, 15),
        "acquisition_cost": Decimal("12000000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 10,
        "residual_value": Decimal("1200000.00"),
    },
    {
        "asset_code": "FA-MACH-006",
        "name": "Industrial Sewing Machine Set",
        "description": "4 industrial sewing machines for upholstery",
        "category": AssetCategory.PLANT_MACHINERY,
        "location": "Upholstery Department",
        "department": "Production",
        "acquisition_date": date(2019, 11, 5),
        "acquisition_cost": Decimal("3200000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 8,
        "residual_value": Decimal("320000.00"),
    },
    {
        "asset_code": "FA-MACH-007",
        "name": "500KVA Generator",
        "description": "Caterpillar standby power generator",
        "category": AssetCategory.PLANT_MACHINERY,
        "location": "Generator House",
        "department": "Facilities",
        "acquisition_date": date(2017, 12, 1),
        "acquisition_cost": Decimal("25000000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 15,
        "residual_value": Decimal("2500000.00"),
    },
    {
        "asset_code": "FA-MACH-008",
        "name": "Dust Collection System",
        "description": "Centralized dust extraction system",
        "category": AssetCategory.PLANT_MACHINERY,
        "location": "Production Floor",
        "department": "Production",
        "acquisition_date": date(2019, 1, 20),
        "acquisition_cost": Decimal("4800000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 10,
        "residual_value": Decimal("480000.00"),
    },
    
    # =========================================================================
    # MOTOR VEHICLES
    # =========================================================================
    {
        "asset_code": "FA-VEH-001",
        "name": "Toyota Hilux - Delivery Truck 1",
        "description": "2022 Toyota Hilux pickup for deliveries",
        "category": AssetCategory.MOTOR_VEHICLES,
        "location": "Vehicle Park",
        "department": "Logistics",
        "assigned_to": "Obinna Madu (Driver)",
        "acquisition_date": date(2022, 4, 10),
        "acquisition_cost": Decimal("28000000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 8,
        "residual_value": Decimal("5600000.00"),
    },
    {
        "asset_code": "FA-VEH-002",
        "name": "Toyota Hilux - Delivery Truck 2",
        "description": "2021 Toyota Hilux pickup for deliveries",
        "category": AssetCategory.MOTOR_VEHICLES,
        "location": "Vehicle Park",
        "department": "Logistics",
        "acquisition_date": date(2021, 6, 15),
        "acquisition_cost": Decimal("25000000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 8,
        "residual_value": Decimal("5000000.00"),
    },
    {
        "asset_code": "FA-VEH-003",
        "name": "Mitsubishi Fuso Truck",
        "description": "10-ton truck for bulk deliveries",
        "category": AssetCategory.MOTOR_VEHICLES,
        "location": "Vehicle Park",
        "department": "Logistics",
        "acquisition_date": date(2020, 9, 1),
        "acquisition_cost": Decimal("35000000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 10,
        "residual_value": Decimal("7000000.00"),
    },
    {
        "asset_code": "FA-VEH-004",
        "name": "Toyota Camry - Executive Car",
        "description": "2023 Toyota Camry for CEO",
        "category": AssetCategory.MOTOR_VEHICLES,
        "location": "Executive Parking",
        "department": "Executive",
        "assigned_to": "Efe Obukohwo (CEO)",
        "acquisition_date": date(2023, 1, 15),
        "acquisition_cost": Decimal("45000000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 6,
        "residual_value": Decimal("9000000.00"),
    },
    {
        "asset_code": "FA-VEH-005",
        "name": "Toyota Corolla - Company Car",
        "description": "2022 Toyota Corolla for CFO",
        "category": AssetCategory.MOTOR_VEHICLES,
        "location": "Executive Parking",
        "department": "Finance",
        "assigned_to": "Adaeze Okonkwo (CFO)",
        "acquisition_date": date(2022, 8, 20),
        "acquisition_cost": Decimal("22000000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 6,
        "residual_value": Decimal("4400000.00"),
    },
    {
        "asset_code": "FA-VEH-006",
        "name": "Forklift - Yale 3-ton",
        "description": "Electric forklift for warehouse operations",
        "category": AssetCategory.MOTOR_VEHICLES,
        "location": "Warehouse",
        "department": "Warehouse",
        "acquisition_date": date(2021, 2, 10),
        "acquisition_cost": Decimal("12000000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 10,
        "residual_value": Decimal("2400000.00"),
    },
    
    # =========================================================================
    # COMPUTER EQUIPMENT
    # =========================================================================
    {
        "asset_code": "FA-COMP-001",
        "name": "Dell Server - Production System",
        "description": "Dell PowerEdge R740 server",
        "category": AssetCategory.COMPUTER_EQUIPMENT,
        "location": "Server Room",
        "department": "IT",
        "acquisition_date": date(2022, 1, 5),
        "acquisition_cost": Decimal("8500000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 5,
        "residual_value": Decimal("850000.00"),
    },
    {
        "asset_code": "FA-COMP-002",
        "name": "Desktop Computers (20 units)",
        "description": "HP ProDesk desktop computers for staff",
        "category": AssetCategory.COMPUTER_EQUIPMENT,
        "location": "Various Offices",
        "department": "IT",
        "acquisition_date": date(2023, 3, 15),
        "acquisition_cost": Decimal("12000000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 4,
        "residual_value": Decimal("1200000.00"),
    },
    {
        "asset_code": "FA-COMP-003",
        "name": "Network Infrastructure",
        "description": "Switches, routers, access points, cabling",
        "category": AssetCategory.COMPUTER_EQUIPMENT,
        "location": "Throughout premises",
        "department": "IT",
        "acquisition_date": date(2021, 6, 1),
        "acquisition_cost": Decimal("5500000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("25"),
        "useful_life_years": 5,
        "residual_value": Decimal("550000.00"),
    },
    
    # =========================================================================
    # FURNITURE & FITTINGS (Office)
    # =========================================================================
    {
        "asset_code": "FA-FURN-001",
        "name": "Executive Office Furniture Set",
        "description": "CEO office - desk, chairs, bookshelf, conference table",
        "category": AssetCategory.FURNITURE_FITTINGS,
        "location": "Executive Office",
        "department": "Executive",
        "acquisition_date": date(2020, 1, 10),
        "acquisition_cost": Decimal("3500000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("20"),
        "useful_life_years": 10,
        "residual_value": Decimal("350000.00"),
    },
    {
        "asset_code": "FA-FURN-002",
        "name": "Finance Department Furniture",
        "description": "Workstations, chairs, filing cabinets",
        "category": AssetCategory.FURNITURE_FITTINGS,
        "location": "Finance Office",
        "department": "Finance",
        "acquisition_date": date(2019, 8, 15),
        "acquisition_cost": Decimal("2800000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("20"),
        "useful_life_years": 10,
        "residual_value": Decimal("280000.00"),
    },
    {
        "asset_code": "FA-FURN-003",
        "name": "Showroom Display Furniture",
        "description": "Display stands and fixtures",
        "category": AssetCategory.FURNITURE_FITTINGS,
        "location": "Showroom",
        "department": "Sales",
        "acquisition_date": date(2020, 3, 1),
        "acquisition_cost": Decimal("4500000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("20"),
        "useful_life_years": 8,
        "residual_value": Decimal("450000.00"),
    },
    
    # =========================================================================
    # OFFICE EQUIPMENT
    # =========================================================================
    {
        "asset_code": "FA-OFEQ-001",
        "name": "Multifunction Printers (5 units)",
        "description": "Ricoh multifunction printers",
        "category": AssetCategory.OFFICE_EQUIPMENT,
        "location": "Various Offices",
        "department": "Administration",
        "acquisition_date": date(2022, 5, 10),
        "acquisition_cost": Decimal("4500000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("20"),
        "useful_life_years": 5,
        "residual_value": Decimal("450000.00"),
    },
    {
        "asset_code": "FA-OFEQ-002",
        "name": "Air Conditioning Units (15 units)",
        "description": "Split AC units throughout premises",
        "category": AssetCategory.OFFICE_EQUIPMENT,
        "location": "Throughout premises",
        "department": "Facilities",
        "acquisition_date": date(2021, 4, 1),
        "acquisition_cost": Decimal("6800000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("20"),
        "useful_life_years": 8,
        "residual_value": Decimal("680000.00"),
    },
    {
        "asset_code": "FA-OFEQ-003",
        "name": "CCTV Security System",
        "description": "32-camera CCTV with recording system",
        "category": AssetCategory.OFFICE_EQUIPMENT,
        "location": "Throughout premises",
        "department": "Security",
        "acquisition_date": date(2020, 11, 15),
        "acquisition_cost": Decimal("3200000.00"),
        "depreciation_method": DepreciationMethod.REDUCING_BALANCE,
        "depreciation_rate": Decimal("20"),
        "useful_life_years": 5,
        "residual_value": Decimal("320000.00"),
    },
]
