"""
Seed Data: Inventory for Efe Obus Furniture Manufacturing LTD
==============================================================
Furniture manufacturing inventory - Raw Materials, Work in Progress, and Finished Goods
"""

from decimal import Decimal

# =============================================================================
# INVENTORY DATA (50+ items)
# =============================================================================

INVENTORY_DATA = [
    # =========================================================================
    # RAW MATERIALS - WOOD
    # =========================================================================
    {
        "sku": "RM-WOOD-001",
        "name": "Mahogany Timber (per cubic meter)",
        "description": "Premium mahogany timber for luxury furniture",
        "category": "Raw Materials - Wood",
        "unit_cost": Decimal("450000.00"),
        "unit_price": Decimal("550000.00"),
        "quantity_on_hand": 25,
        "reorder_level": 10,
        "reorder_quantity": 20,
        "unit_of_measure": "cbm",
    },
    {
        "sku": "RM-WOOD-002",
        "name": "Iroko Timber (per cubic meter)",
        "description": "Durable iroko wood for outdoor furniture",
        "category": "Raw Materials - Wood",
        "unit_cost": Decimal("380000.00"),
        "unit_price": Decimal("460000.00"),
        "quantity_on_hand": 30,
        "reorder_level": 12,
        "reorder_quantity": 25,
        "unit_of_measure": "cbm",
    },
    {
        "sku": "RM-WOOD-003",
        "name": "Obeche Timber (per cubic meter)",
        "description": "Light obeche wood for interior furniture",
        "category": "Raw Materials - Wood",
        "unit_cost": Decimal("220000.00"),
        "unit_price": Decimal("280000.00"),
        "quantity_on_hand": 40,
        "reorder_level": 15,
        "reorder_quantity": 30,
        "unit_of_measure": "cbm",
    },
    {
        "sku": "RM-WOOD-004",
        "name": "Plywood Sheet (8x4 ft, 18mm)",
        "description": "Standard 18mm plywood sheets",
        "category": "Raw Materials - Wood",
        "unit_cost": Decimal("18000.00"),
        "unit_price": Decimal("22000.00"),
        "quantity_on_hand": 200,
        "reorder_level": 50,
        "reorder_quantity": 100,
        "unit_of_measure": "sheet",
    },
    {
        "sku": "RM-WOOD-005",
        "name": "MDF Board (8x4 ft, 18mm)",
        "description": "Medium Density Fibreboard for cabinets",
        "category": "Raw Materials - Wood",
        "unit_cost": Decimal("22000.00"),
        "unit_price": Decimal("28000.00"),
        "quantity_on_hand": 150,
        "reorder_level": 40,
        "reorder_quantity": 80,
        "unit_of_measure": "sheet",
    },
    {
        "sku": "RM-WOOD-006",
        "name": "Particle Board (8x4 ft, 16mm)",
        "description": "Economy particle board for backing",
        "category": "Raw Materials - Wood",
        "unit_cost": Decimal("8000.00"),
        "unit_price": Decimal("12000.00"),
        "quantity_on_hand": 100,
        "reorder_level": 30,
        "reorder_quantity": 50,
        "unit_of_measure": "sheet",
    },
    
    # =========================================================================
    # RAW MATERIALS - UPHOLSTERY
    # =========================================================================
    {
        "sku": "RM-UPH-001",
        "name": "Premium Leather (per sq meter)",
        "description": "Top grain leather for executive furniture",
        "category": "Raw Materials - Upholstery",
        "unit_cost": Decimal("35000.00"),
        "unit_price": Decimal("45000.00"),
        "quantity_on_hand": 100,
        "reorder_level": 25,
        "reorder_quantity": 50,
        "unit_of_measure": "sqm",
    },
    {
        "sku": "RM-UPH-002",
        "name": "Bonded Leather (per sq meter)",
        "description": "Quality bonded leather for standard furniture",
        "category": "Raw Materials - Upholstery",
        "unit_cost": Decimal("18000.00"),
        "unit_price": Decimal("25000.00"),
        "quantity_on_hand": 150,
        "reorder_level": 40,
        "reorder_quantity": 80,
        "unit_of_measure": "sqm",
    },
    {
        "sku": "RM-UPH-003",
        "name": "Velvet Fabric (per meter)",
        "description": "Luxury velvet for sofas and chairs",
        "category": "Raw Materials - Upholstery",
        "unit_cost": Decimal("8500.00"),
        "unit_price": Decimal("12000.00"),
        "quantity_on_hand": 200,
        "reorder_level": 50,
        "reorder_quantity": 100,
        "unit_of_measure": "meter",
    },
    {
        "sku": "RM-UPH-004",
        "name": "Cotton Fabric (per meter)",
        "description": "Quality cotton for cushions and pillows",
        "category": "Raw Materials - Upholstery",
        "unit_cost": Decimal("3500.00"),
        "unit_price": Decimal("5500.00"),
        "quantity_on_hand": 300,
        "reorder_level": 80,
        "reorder_quantity": 150,
        "unit_of_measure": "meter",
    },
    {
        "sku": "RM-UPH-005",
        "name": "High Density Foam (per cubic meter)",
        "description": "Durable foam for seating",
        "category": "Raw Materials - Upholstery",
        "unit_cost": Decimal("85000.00"),
        "unit_price": Decimal("110000.00"),
        "quantity_on_hand": 30,
        "reorder_level": 10,
        "reorder_quantity": 20,
        "unit_of_measure": "cbm",
    },
    {
        "sku": "RM-UPH-006",
        "name": "Medium Density Foam (per cubic meter)",
        "description": "Standard foam for cushions",
        "category": "Raw Materials - Upholstery",
        "unit_cost": Decimal("55000.00"),
        "unit_price": Decimal("75000.00"),
        "quantity_on_hand": 40,
        "reorder_level": 15,
        "reorder_quantity": 25,
        "unit_of_measure": "cbm",
    },
    
    # =========================================================================
    # RAW MATERIALS - HARDWARE
    # =========================================================================
    {
        "sku": "RM-HW-001",
        "name": "Wood Screws Assorted (box of 1000)",
        "description": "Assorted wood screws for furniture assembly",
        "category": "Raw Materials - Hardware",
        "unit_cost": Decimal("8500.00"),
        "unit_price": Decimal("12000.00"),
        "quantity_on_hand": 50,
        "reorder_level": 15,
        "reorder_quantity": 30,
        "unit_of_measure": "box",
    },
    {
        "sku": "RM-HW-002",
        "name": "Cabinet Hinges (pair)",
        "description": "Soft-close cabinet hinges",
        "category": "Raw Materials - Hardware",
        "unit_cost": Decimal("1200.00"),
        "unit_price": Decimal("1800.00"),
        "quantity_on_hand": 500,
        "reorder_level": 100,
        "reorder_quantity": 200,
        "unit_of_measure": "pair",
    },
    {
        "sku": "RM-HW-003",
        "name": "Drawer Slides (pair, 18 inch)",
        "description": "Ball bearing drawer slides",
        "category": "Raw Materials - Hardware",
        "unit_cost": Decimal("3500.00"),
        "unit_price": Decimal("5000.00"),
        "quantity_on_hand": 200,
        "reorder_level": 50,
        "reorder_quantity": 100,
        "unit_of_measure": "pair",
    },
    {
        "sku": "RM-HW-004",
        "name": "Cabinet Handles (set of 10)",
        "description": "Modern cabinet handles - brushed nickel",
        "category": "Raw Materials - Hardware",
        "unit_cost": Decimal("4500.00"),
        "unit_price": Decimal("6500.00"),
        "quantity_on_hand": 100,
        "reorder_level": 25,
        "reorder_quantity": 50,
        "unit_of_measure": "set",
    },
    {
        "sku": "RM-HW-005",
        "name": "Cabinet Locks (each)",
        "description": "Security cabinet locks with keys",
        "category": "Raw Materials - Hardware",
        "unit_cost": Decimal("2500.00"),
        "unit_price": Decimal("3800.00"),
        "quantity_on_hand": 80,
        "reorder_level": 20,
        "reorder_quantity": 40,
        "unit_of_measure": "pcs",
    },
    
    # =========================================================================
    # RAW MATERIALS - FINISHING
    # =========================================================================
    {
        "sku": "RM-FIN-001",
        "name": "Wood Varnish (20 liters)",
        "description": "Clear wood varnish for finishing",
        "category": "Raw Materials - Finishing",
        "unit_cost": Decimal("45000.00"),
        "unit_price": Decimal("60000.00"),
        "quantity_on_hand": 30,
        "reorder_level": 10,
        "reorder_quantity": 20,
        "unit_of_measure": "drum",
    },
    {
        "sku": "RM-FIN-002",
        "name": "Wood Stain - Mahogany (5 liters)",
        "description": "Mahogany wood stain for color matching",
        "category": "Raw Materials - Finishing",
        "unit_cost": Decimal("18000.00"),
        "unit_price": Decimal("25000.00"),
        "quantity_on_hand": 20,
        "reorder_level": 8,
        "reorder_quantity": 15,
        "unit_of_measure": "can",
    },
    {
        "sku": "RM-FIN-003",
        "name": "Sandpaper Assorted (pack of 100)",
        "description": "Assorted grits sandpaper sheets",
        "category": "Raw Materials - Finishing",
        "unit_cost": Decimal("12000.00"),
        "unit_price": Decimal("18000.00"),
        "quantity_on_hand": 25,
        "reorder_level": 8,
        "reorder_quantity": 15,
        "unit_of_measure": "pack",
    },
    {
        "sku": "RM-FIN-004",
        "name": "Wood Filler (5kg)",
        "description": "Wood filler for repairs and finishing",
        "category": "Raw Materials - Finishing",
        "unit_cost": Decimal("8500.00"),
        "unit_price": Decimal("12000.00"),
        "quantity_on_hand": 20,
        "reorder_level": 8,
        "reorder_quantity": 12,
        "unit_of_measure": "bucket",
    },
    {
        "sku": "RM-FIN-005",
        "name": "Wood Glue (5 liters)",
        "description": "Industrial strength wood glue",
        "category": "Raw Materials - Finishing",
        "unit_cost": Decimal("15000.00"),
        "unit_price": Decimal("22000.00"),
        "quantity_on_hand": 25,
        "reorder_level": 10,
        "reorder_quantity": 15,
        "unit_of_measure": "can",
    },
    
    # =========================================================================
    # FINISHED GOODS - LIVING ROOM
    # =========================================================================
    {
        "sku": "FG-LIV-001",
        "name": "Executive 7-Seater Sofa Set",
        "description": "Luxury leather 7-seater sofa set (3+2+2 configuration)",
        "category": "Finished Goods - Living Room",
        "unit_cost": Decimal("850000.00"),
        "unit_price": Decimal("1350000.00"),
        "quantity_on_hand": 5,
        "reorder_level": 2,
        "reorder_quantity": 3,
        "unit_of_measure": "set",
    },
    {
        "sku": "FG-LIV-002",
        "name": "Standard 5-Seater Sofa Set",
        "description": "Fabric 5-seater sofa set (3+2 configuration)",
        "category": "Finished Goods - Living Room",
        "unit_cost": Decimal("450000.00"),
        "unit_price": Decimal("750000.00"),
        "quantity_on_hand": 8,
        "reorder_level": 3,
        "reorder_quantity": 5,
        "unit_of_measure": "set",
    },
    {
        "sku": "FG-LIV-003",
        "name": "Center Table - Glass Top",
        "description": "Mahogany center table with tempered glass top",
        "category": "Finished Goods - Living Room",
        "unit_cost": Decimal("75000.00"),
        "unit_price": Decimal("145000.00"),
        "quantity_on_hand": 12,
        "reorder_level": 5,
        "reorder_quantity": 8,
        "unit_of_measure": "pcs",
    },
    {
        "sku": "FG-LIV-004",
        "name": "TV Console - 6ft",
        "description": "Modern TV console with storage",
        "category": "Finished Goods - Living Room",
        "unit_cost": Decimal("120000.00"),
        "unit_price": Decimal("220000.00"),
        "quantity_on_hand": 10,
        "reorder_level": 4,
        "reorder_quantity": 6,
        "unit_of_measure": "pcs",
    },
    {
        "sku": "FG-LIV-005",
        "name": "Bookshelf - 5 Tier",
        "description": "Solid wood 5-tier bookshelf",
        "category": "Finished Goods - Living Room",
        "unit_cost": Decimal("85000.00"),
        "unit_price": Decimal("165000.00"),
        "quantity_on_hand": 8,
        "reorder_level": 3,
        "reorder_quantity": 5,
        "unit_of_measure": "pcs",
    },
    
    # =========================================================================
    # FINISHED GOODS - DINING
    # =========================================================================
    {
        "sku": "FG-DIN-001",
        "name": "6-Seater Dining Set",
        "description": "Mahogany dining table with 6 upholstered chairs",
        "category": "Finished Goods - Dining",
        "unit_cost": Decimal("380000.00"),
        "unit_price": Decimal("650000.00"),
        "quantity_on_hand": 6,
        "reorder_level": 2,
        "reorder_quantity": 4,
        "unit_of_measure": "set",
    },
    {
        "sku": "FG-DIN-002",
        "name": "8-Seater Dining Set",
        "description": "Premium iroko dining table with 8 chairs",
        "category": "Finished Goods - Dining",
        "unit_cost": Decimal("520000.00"),
        "unit_price": Decimal("950000.00"),
        "quantity_on_hand": 4,
        "reorder_level": 2,
        "reorder_quantity": 3,
        "unit_of_measure": "set",
    },
    {
        "sku": "FG-DIN-003",
        "name": "Bar Stool (each)",
        "description": "High bar stool with leather cushion",
        "category": "Finished Goods - Dining",
        "unit_cost": Decimal("35000.00"),
        "unit_price": Decimal("65000.00"),
        "quantity_on_hand": 20,
        "reorder_level": 8,
        "reorder_quantity": 12,
        "unit_of_measure": "pcs",
    },
    
    # =========================================================================
    # FINISHED GOODS - BEDROOM
    # =========================================================================
    {
        "sku": "FG-BED-001",
        "name": "King Size Bed Frame",
        "description": "Solid wood king size bed frame with headboard",
        "category": "Finished Goods - Bedroom",
        "unit_cost": Decimal("280000.00"),
        "unit_price": Decimal("480000.00"),
        "quantity_on_hand": 8,
        "reorder_level": 3,
        "reorder_quantity": 5,
        "unit_of_measure": "pcs",
    },
    {
        "sku": "FG-BED-002",
        "name": "Queen Size Bed Frame",
        "description": "Solid wood queen size bed frame with headboard",
        "category": "Finished Goods - Bedroom",
        "unit_cost": Decimal("220000.00"),
        "unit_price": Decimal("380000.00"),
        "quantity_on_hand": 10,
        "reorder_level": 4,
        "reorder_quantity": 6,
        "unit_of_measure": "pcs",
    },
    {
        "sku": "FG-BED-003",
        "name": "Wardrobe - 3 Door",
        "description": "Large 3-door wardrobe with mirror",
        "category": "Finished Goods - Bedroom",
        "unit_cost": Decimal("320000.00"),
        "unit_price": Decimal("550000.00"),
        "quantity_on_hand": 6,
        "reorder_level": 2,
        "reorder_quantity": 4,
        "unit_of_measure": "pcs",
    },
    {
        "sku": "FG-BED-004",
        "name": "Dresser with Mirror",
        "description": "Bedroom dresser with attached mirror",
        "category": "Finished Goods - Bedroom",
        "unit_cost": Decimal("145000.00"),
        "unit_price": Decimal("280000.00"),
        "quantity_on_hand": 8,
        "reorder_level": 3,
        "reorder_quantity": 5,
        "unit_of_measure": "pcs",
    },
    {
        "sku": "FG-BED-005",
        "name": "Nightstand (pair)",
        "description": "Matching pair of bedside nightstands",
        "category": "Finished Goods - Bedroom",
        "unit_cost": Decimal("65000.00"),
        "unit_price": Decimal("120000.00"),
        "quantity_on_hand": 12,
        "reorder_level": 5,
        "reorder_quantity": 8,
        "unit_of_measure": "pair",
    },
    
    # =========================================================================
    # FINISHED GOODS - OFFICE
    # =========================================================================
    {
        "sku": "FG-OFF-001",
        "name": "Executive Desk",
        "description": "Large executive desk with drawers",
        "category": "Finished Goods - Office",
        "unit_cost": Decimal("280000.00"),
        "unit_price": Decimal("480000.00"),
        "quantity_on_hand": 10,
        "reorder_level": 4,
        "reorder_quantity": 6,
        "unit_of_measure": "pcs",
    },
    {
        "sku": "FG-OFF-002",
        "name": "Executive Chair - Leather",
        "description": "High-back leather executive chair",
        "category": "Finished Goods - Office",
        "unit_cost": Decimal("125000.00"),
        "unit_price": Decimal("220000.00"),
        "quantity_on_hand": 15,
        "reorder_level": 5,
        "reorder_quantity": 10,
        "unit_of_measure": "pcs",
    },
    {
        "sku": "FG-OFF-003",
        "name": "Staff Desk - L-Shaped",
        "description": "L-shaped workstation desk",
        "category": "Finished Goods - Office",
        "unit_cost": Decimal("95000.00"),
        "unit_price": Decimal("175000.00"),
        "quantity_on_hand": 20,
        "reorder_level": 8,
        "reorder_quantity": 12,
        "unit_of_measure": "pcs",
    },
    {
        "sku": "FG-OFF-004",
        "name": "Visitor Chair",
        "description": "Office visitor chair with armrests",
        "category": "Finished Goods - Office",
        "unit_cost": Decimal("35000.00"),
        "unit_price": Decimal("65000.00"),
        "quantity_on_hand": 30,
        "reorder_level": 10,
        "reorder_quantity": 15,
        "unit_of_measure": "pcs",
    },
    {
        "sku": "FG-OFF-005",
        "name": "Filing Cabinet - 4 Drawer",
        "description": "Metal filing cabinet with lock",
        "category": "Finished Goods - Office",
        "unit_cost": Decimal("85000.00"),
        "unit_price": Decimal("145000.00"),
        "quantity_on_hand": 15,
        "reorder_level": 5,
        "reorder_quantity": 10,
        "unit_of_measure": "pcs",
    },
    {
        "sku": "FG-OFF-006",
        "name": "Conference Table - 12 Seater",
        "description": "Large boardroom conference table",
        "category": "Finished Goods - Office",
        "unit_cost": Decimal("450000.00"),
        "unit_price": Decimal("850000.00"),
        "quantity_on_hand": 3,
        "reorder_level": 1,
        "reorder_quantity": 2,
        "unit_of_measure": "pcs",
    },
    {
        "sku": "FG-OFF-007",
        "name": "Reception Counter",
        "description": "Modern reception desk with storage",
        "category": "Finished Goods - Office",
        "unit_cost": Decimal("280000.00"),
        "unit_price": Decimal("520000.00"),
        "quantity_on_hand": 4,
        "reorder_level": 2,
        "reorder_quantity": 3,
        "unit_of_measure": "pcs",
    },
    
    # =========================================================================
    # FINISHED GOODS - OUTDOOR
    # =========================================================================
    {
        "sku": "FG-OUT-001",
        "name": "Garden Bench - 3 Seater",
        "description": "Weather-resistant outdoor bench",
        "category": "Finished Goods - Outdoor",
        "unit_cost": Decimal("85000.00"),
        "unit_price": Decimal("165000.00"),
        "quantity_on_hand": 10,
        "reorder_level": 4,
        "reorder_quantity": 6,
        "unit_of_measure": "pcs",
    },
    {
        "sku": "FG-OUT-002",
        "name": "Patio Set - 4 Seater",
        "description": "Outdoor patio table with 4 chairs",
        "category": "Finished Goods - Outdoor",
        "unit_cost": Decimal("180000.00"),
        "unit_price": Decimal("350000.00"),
        "quantity_on_hand": 6,
        "reorder_level": 2,
        "reorder_quantity": 4,
        "unit_of_measure": "set",
    },
]
